component_id: urn:publicid:aist-se1
component_manager_id: urn:publicid:IDN+AIST+authority+serm

vlan_trans: true
qinq: false
capacity: 1G


interfaces:
    eth1:
        remote_endpoints: 
            -
                name: urn:publicid:psnc-nsi:if1
                type: nsi
                vlans:
                    - 1000
                    - 2000
                    - 3000-3030
            -
                name: urn:publicid:psnc-nsi:if2
                type: nsi
                vlans:
                    - 1000
                    - 2000
                    - 3000-3030

    eth2:
        remote_endpoints:
            -
                name: urn:publicid:psnc-dpid:if2
                type: static
                vlans:
                    - 1000
