component_id: urn:publicid:aist-se1
component_manager_id: urn:publicid:IDN+AIST+authority+serm

vlan_trans: true
qinq: false
capacity: 1G


interfaces:
    "1":
        remote_endpoints: 
            -
                name: urn:publicid:psnc-nsi:if1
                type: vlan_trans
                vlans:
                    - 1000-1001
            -
                name: urn:publicid:psnc-nsi:if2
                type: vlan_trans
                vlans:
                    - 2000-2002

    "2":
        remote_endpoints:
            -
                name: urn:publicid:psnc-dpid:if2
                type: static_link
                vlans:
                    - 1000
